### ISSUE TITLE
test: Repository 클래스 테스트 코드 작성

### ISSUE THREAD

**Issue by choigy1001** [CheoCharm/MapZ-Server#138]
# 문제 상황
> Data JPA 메서드는 검증이 필요없으나, QueryDSL 메서드는 우리가 작성하다보니 정확성을 보장받지 못함

# 해결 방법
> 테스트 코드 작성하여 검증 진행

# To-Do
- [x] UserRepository 클래스 테스트 코드 작성
- [x] GroupRepository 클래스 테스트 코드 작성
- [x] UserGroupRepository 클래스 테스트 코드 작성
