### ISSUE TITLE
fix: GET 메서드 body

### ISSUE THREAD

**Issue by choigy1001** [CheoCharm/MapZ-Server#90]
# 문제 상황
> 프론트에서 GET 메서드에 body 담아서 보낼시 예외가 터짐

# 해결 방법
> POST로 바꾸거나 파라미터로 넘기는 방법 선택

# To-Do
- [ ] 이메일, 비밀번호 유효성 검사 API
- [ ] 비밀번호 찾기 API
- [ ] 그룹 조회 API
